name: Update Lists

on:
  push:
    paths:
      - "**.py"
      - "**.sh"
      - "**.yml"
      - "**.toml"
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          check-latest: true
          cache: "pip"

      - name: Check Python3 Version
        run: python3 --version

      - name: Install Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Generating IP Lists
        run: python3 ./src/list_generator.py

      - name: Generating CIDR Lists
        run: python3 ./src/generate_cidr.py

      - name: Generating RouterOS Lists
        run: python3 ./src/router_os_list.py

      - name: Update IP count in README.md
        run: |
          TOTAL_IPS=$(wc -l lists/ipv?.txt | grep -oP '\d+(?=\s+total)')
          sed -i "s/^\*\*[0-9][0-9]*\*\*$/**$TOTAL_IPS**/" README.md

      - name: Commit changes
        run: |
          git config --local user.email '22249844+KostikShutov@users.noreply.github.com'
          git config --local user.name 'KostikShutov'
          git add lists/ README.md
          git commit -m 'Updated Lists [Automated]'
          git pull
          git push

      - name: Check diff
        run: git diff HEAD~1..HEAD
